/* ==========================================================================
   CORRETORA DE MILHÕES — Dados fictícios (seed)
   Usado só na primeira visita para popular o "banco" local (ver store.js).
   Nomes, contatos e imóveis são fictícios, feitos para demonstração.
   ========================================================================== */

const PERFIL_SEED = {
  nome: 'Camila Vasconcelos',
  creci: 'CRECI-PE 78341',
  bio: 'Conhecida como Corretora de Milhões, corretora de imóveis independente há 8 anos, especializada em apartamentos e casas de alto padrão na Zona Sul do Recife. Atendimento próximo, transparente e sem pressa, do primeiro contato até a entrega das chaves.',
  regiao_atuacao: 'Recife, Boa Viagem, Casa Forte, Piedade e região',
  whatsapp: '5581988887777',
  email: 'contato@corretorademilhoes.exemplo.com',
  instagram_url: 'https://instagram.com/corretorademilhoes',
  facebook_url: 'https://facebook.com/corretorademilhoes',
  endereco_escritorio: 'Av. Boa Viagem, 1000 - Recife/PE',
  latitude: -8.1197,
  longitude: -34.9020,
};

const IMOVEIS_SEED = [
  {
    codigo_referencia: 'CM-0001',
    titulo: 'Apartamento Vista Mar 3 Quartos',
    descricao: 'Apartamento reformado a poucos metros da praia de Boa Viagem, com vista mar parcial, varanda gourmet e sol da manhã. Prédio com portaria 24h, piscina e academia.',
    tipo_negocio: 'venda',
    tipo_imovel: 'apartamento',
    status: 'disponivel',
    valor: 890000,
    valor_condominio: 980,
    valor_iptu: 210,
    area_construida: 110,
    area_terreno: null,
    quartos: 3, suites: 1, banheiros: 3, vagas_garagem: 2,
    cidade: 'Recife', bairro: 'Boa Viagem', endereco: 'Av. Boa Viagem, próx. ao Shopping Recife', cep: '51030-000',
    latitude: -8.1256, longitude: -34.9008,
    destaque: true, video_url: '',
    fotos: ['demo-0-0.jpg', 'demo-0-1.jpg', 'demo-0-2.jpg'],
  },
  {
    codigo_referencia: 'CM-0002',
    titulo: 'Casa em Condomínio Fechado',
    descricao: 'Casa térrea em condomínio fechado, quintal amplo com espaço gourmet, 4 quartos sendo 2 suítes. Condomínio com segurança 24h, área verde e salão de festas.',
    tipo_negocio: 'venda',
    tipo_imovel: 'casa_condominio',
    status: 'disponivel',
    valor: 1250000,
    valor_condominio: 650,
    valor_iptu: 340,
    area_construida: 220, area_terreno: 300,
    quartos: 4, suites: 2, banheiros: 4, vagas_garagem: 3,
    cidade: 'Recife', bairro: 'Casa Forte', endereco: 'Rua Real da Torre, próx. ao Parque de Casa Forte', cep: '52061-000',
    latitude: -8.0328, longitude: -34.9147,
    destaque: true, video_url: '',
    fotos: ['demo-1-0.jpg', 'demo-1-1.jpg', 'demo-1-2.jpg'],
  },
  {
    codigo_referencia: 'CM-0003',
    titulo: 'Cobertura Duplex Piedade',
    descricao: 'Cobertura duplex com piscina privativa e terraço gourmet, vista aberta para o mar. Disponível para venda ou aluguel, ideal tanto para moradia quanto para investimento.',
    tipo_negocio: 'venda_aluguel',
    tipo_imovel: 'cobertura',
    status: 'disponivel',
    valor: 1980000,
    valor_condominio: 1450,
    valor_iptu: 480,
    area_construida: 280, area_terreno: null,
    quartos: 4, suites: 3, banheiros: 5, vagas_garagem: 4,
    cidade: 'Jaboatão dos Guararapes', bairro: 'Piedade', endereco: 'Av. Bernardo Vieira de Melo, próx. à praia', cep: '54410-010',
    latitude: -8.1810, longitude: -34.9080,
    destaque: true, video_url: '',
    fotos: ['demo-2-0.jpg', 'demo-2-1.jpg', 'demo-2-2.jpg'],
  },
  {
    codigo_referencia: 'CM-0004',
    titulo: 'Apartamento Compacto Centro',
    descricao: 'Apartamento compacto e bem localizado, ideal para quem trabalha no centro do Recife. Prédio com elevador, próximo a estações de metrô e ônibus.',
    tipo_negocio: 'aluguel',
    tipo_imovel: 'apartamento',
    status: 'disponivel',
    valor: 2200,
    valor_condominio: 420,
    valor_iptu: 60,
    area_construida: 45, area_terreno: null,
    quartos: 1, suites: 0, banheiros: 1, vagas_garagem: 1,
    cidade: 'Recife', bairro: 'Boa Vista', endereco: 'Rua da Aurora, próx. ao Marco Zero', cep: '50050-000',
    latitude: -8.0631, longitude: -34.8802,
    destaque: false, video_url: '',
    fotos: ['demo-3-0.jpg', 'demo-3-1.jpg', 'demo-3-2.jpg'],
  },
  {
    codigo_referencia: 'CM-0005',
    titulo: 'Casa de Praia Vendida',
    descricao: 'Casa de praia a 200m do mar, 3 suítes, piscina e churrasqueira. Negócio fechado recentemente, mantida na vitrine como referência de negócio concluído.',
    tipo_negocio: 'venda',
    tipo_imovel: 'casa',
    status: 'vendido',
    valor: 760000,
    valor_condominio: null,
    valor_iptu: 150,
    area_construida: 160, area_terreno: 400,
    quartos: 3, suites: 3, banheiros: 4, vagas_garagem: 2,
    cidade: 'Ipojuca', bairro: 'Porto de Galinhas', endereco: 'Rua das Piscinas Naturais', cep: '55590-000',
    latitude: -8.5083, longitude: -35.0028,
    destaque: false, video_url: '',
    fotos: ['demo-4-0.jpg', 'demo-4-1.jpg', 'demo-4-2.jpg'],
  },
  {
    codigo_referencia: 'CM-0006',
    titulo: 'Terreno em Aldeia',
    descricao: 'Terreno plano em condomínio horizontal, pronto para construir. Área verde preservada, segurança 24h e infraestrutura completa.',
    tipo_negocio: 'venda',
    tipo_imovel: 'terreno',
    status: 'disponivel',
    valor: 450000,
    valor_condominio: 380,
    valor_iptu: 90,
    area_construida: null, area_terreno: 600,
    quartos: 0, suites: 0, banheiros: 0, vagas_garagem: 0,
    cidade: 'Camaragibe', bairro: 'Aldeia', endereco: 'Estrada de Aldeia, km 3', cep: '54786-000',
    latitude: -8.0206, longitude: -35.0203,
    destaque: false, video_url: '',
    fotos: [],
  },
  {
    codigo_referencia: 'CM-0007',
    titulo: 'Sala Comercial Boa Viagem',
    descricao: 'Sala comercial em prédio corporativo, pronta para uso, com recepção compartilhada e vaga de garagem inclusa.',
    tipo_negocio: 'aluguel',
    tipo_imovel: 'comercial',
    status: 'reservado',
    valor: 3500,
    valor_condominio: 890,
    valor_iptu: 120,
    area_construida: 60, area_terreno: null,
    quartos: 0, suites: 0, banheiros: 1, vagas_garagem: 1,
    cidade: 'Recife', bairro: 'Boa Viagem', endereco: 'Av. Domingos Ferreira, próx. ao Shopping Recife', cep: '51011-050',
    latitude: -8.1180, longitude: -34.8990,
    destaque: false, video_url: '',
    fotos: [],
  },
];

const DEPOIMENTOS_SEED = [
  { nome_cliente: 'Juliana Alves', email_cliente: '', texto: 'Atendimento impecável, me senti segura em cada etapa da compra.', nota: 5, aprovado: true, imovel_codigo: 'CM-0001' },
  { nome_cliente: 'Rodrigo Melo', email_cliente: '', texto: 'Encontrou o imóvel ideal em menos de duas semanas. Recomendo!', nota: 5, aprovado: true, imovel_codigo: null },
  { nome_cliente: 'Camila Torres', email_cliente: '', texto: 'Profissional atenciosa e muito transparente na negociação.', nota: 4, aprovado: true, imovel_codigo: null },
  { nome_cliente: 'Fernando Dias', email_cliente: '', texto: 'Superou minhas expectativas, recomendo demais! Processo rápido e sem burocracia.', nota: 5, aprovado: false, imovel_codigo: 'CM-0003' },
];

const REALIZACOES_SEED = [
  { titulo: 'Mais uma chave entregue em Porto de Galinhas!', texto: 'Negociação concluída em 20 dias, do primeiro contato até a assinatura.', foto: 'realizacao-demo.jpg', visivel: true, imovel_codigo: 'CM-0005' },
  { titulo: 'Negócio fechado em tempo recorde!', texto: 'Mais uma família realizando o sonho da casa própria com tranquilidade.', foto: 'realizacao-demo.jpg', visivel: true, imovel_codigo: null },
];
